const sampleData = 
[
    {
      title: "Seeds",
      description: "High-quality seeds for your garden or farm, carefully selected for optimal growth.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1621459565612-97fb9e4ed9d9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcwNjMyNTE4Mg&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price:  900,
      location: "SeedHub Farm" ,
      country: "India",
      contact:1111111111,
    },
    {
      title: "Coffee",
      description: "Premium coffee beans sourced from sustainable and ethical farms around the world.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1509785307050-d4066910ec1e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcwNjMyNTI4Ng&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price: 1100,
      location: "BeanBliss Plantations , Assam",
      country: "India",
      contact:1111111111,
    },
    {
      title: "Tea",
      description: "Delicious and aromatic tea leaves, handpicked from the finest tea gardens.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcwNjMyNTAxOA&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price: 1000,
      location: "ZenTea Estates , Orrisa",
      country: "India",
      contact:1111111111,
    },
    {
      title: "Spices",
      description: "Aromatic and flavorful spices to enhance your culinary creations, sourced from spice-rich regions.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1633633688057-9bd3ed288d52?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcwNjMyNDc5OQ&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price: 1500,
      location: "SpiceHaven Farm , Karnataka ",
      country: "India",
      contact:1111111111,
    },
    {
      title: "Cow Milk",
      description: "Fresh and wholesome cow milk from our pasture-raised, happy cows.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1585083969600-495ee7e3604b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcwNjMyNTQ4MQ&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price: 500,
      location: "HappyCows Dairy and Farm , Gir Gujarat",
      country: "India",
      contact:1111111111,
    },
    {
      title: " Pure Honey",
      description: "Pure, golden honey harvested from our organic beehives in the countryside.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1587049352851-8d4e89133924?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcwMDk3NTQzNA&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price: 600,
      location: "BeeHaven Farm , Maharashtra",
      country: "India",
      contact:1111111111,
    },
    {
      title: "Berries",
      description: "A delightful mix of organic berries, bursting with flavor and packed with antioxidants.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1444459094717-a39f1e3e0903?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcwNjMyNTcyOA&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price: 670,
      location: "BerryBounty Farm , Himachal Pradesh",
      country: "India",
    },
    {
      title: "Carrots",
      description: "Fresh and crisp organic carrots, rich in vitamins and perfect for a healthy snack or cooking.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8dyxoLGZpdCxhdXRvLGRwcnx8fHx8fDE3MDU4MTUwMzc&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price: 199,
      location: "CarrotCraze Gardens Farms , Haryana",
      country: "India",
      contact:1111111111,
    },
    {
      title: "Green Breeze Herbs",
      description: "A collection of fresh and aromatic organic herbs,Used in Ayurveda and also perfect for adding flavor to your dishes.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1532091710512-26fd3b2dcf16?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcwNjMyNTc5MQ&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price: 400,
      location: "GreenBreeze Herb Farm  , Aravalis",
      country: "India",
      contact:1111111111,
    },
    {
      title: "Nature's Best Avocado",
      description: "Creamy and nutrient-rich avocados, handpicked from nature's best orchards for your culinary delight.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1580823673202-ef0405ae5b52?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcwNjMyNTgyMw&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price: 500,
      location: "AvocadoHaven Plantations , Tamil Nadu",
      country: "India",
      contact:1111111111,
    },
    {
      title: "Green Harbor Basil",
      description: "Organic basil with a delightful aroma, ideal for enhancing the flavor of your favorite dishes.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1558070510-504a0db43997?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcwMzE5MTM0Mg&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price: 340,
      location: "GreenHarbor Herb Gardens , Himachal Pradesh",
      country: "India",
      contact:1111111111,
    },
    {
      title: "Pure Oranges",
      description: "Juicy and sweet organic oranges, bursting with pure citrus goodness and natural freshness.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1597714026720-8f74c62310ba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcwNjMyNTg4Ng&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price: 200,
      location: "OrangeGrove Farms , Maharashtra",
      country: "India",
      contact:1111111111,
    },
    {
      title: "Fresh Root Ginger",
      description: "Spicy and aromatic organic ginger roots, perfect for adding a kick to your culinary creations.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1603431777782-912e3b76f60d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcwNjMyNTkxMg&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price: 250,
      location: "GingerRoot Gardens , Arunachal Pradesh",
      country: "India",
      contact:1111111111,
    },
    {
      title: "Eco Crisp Apples",
      description: "Crisp and refreshing organic apples, grown in an eco-friendly orchard for guilt-free snacking.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1576179635662-9d1983e97e1e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcwNjMyNTk0NA&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price: 350,
      location: "EcoCrisp Orchards , Shimla",
      country: "India",
      contact:1111111111,
    },
    {
      title: "Bio Bloom Flowers",
      description: "A vibrant assortment of organic flowers, perfect for brightening up your space or gifting.",
      image:{
      filename: "productimage",
      url: "https://plus.unsplash.com/premium_photo-1670574872504-56cdb36ffa64?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcwNjMyNTk3Mg&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price: 150,
      location: "BioBloom Florals , Kerala",
      country: "India",
      contact:1111111111,
    },
    {
      title: "Green Zest Lemons",
      description: "Zesty and organic lemons, packed with natural citrus flavor for your culinary creations.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1432457990754-c8b5f21448de?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcwNjMyNjAwMA&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price: 185,
      location: "Zestful Lemon Groves , Gujarat",
      country: "India",
      contact:1111111111,
    },
    {
      title: "Fertilizers",
      description: "Organic and eco-friendly fertilizers to nourish your soil and promote healthy plant growth.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1705592675280-8025803f4a5f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcwNjMyNjAzMw&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price:1200,
      location: "EcoGrow Solutions",
      country: "India",
      contact:1111111111,
    },
    {
      title: "Hair Oil",
      description: "Natural and nourishing hair oil to promote healthy and shiny hair.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1608571423539-e951b9b3871e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcwNjMyNjA2NA&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price: 400,
      location: "GlowLocks Wellness , Kerala",
      country: "India",
      contact:1111111111,
    },
    {
      title: "Dry Fruits",
      description: "Assorted dry fruits for a nutritious and energy-packed snacking experience.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1598371624230-a7bdd72e0d22?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcwNjMyNjA5NQ&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price:300,
      location: "NutriCrunch Farms , Kashmir",
      country: "India",
      contact:1111111111,
    },
    {
      title: "Kesar",
      description: "Premium saffron (kesar) known for its rich flavor and aromatic properties.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1616429266184-7455498d96db?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcwNjMyNjExNw&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price: 900,
      location: "SaffronGlow Plantations , Jammu Kashmir",
      country: "India",
      contact:1111111111,
    },
    {
      title: "Different Flours",
      description: "A variety of high-quality flours for your baking and cooking needs.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1545587195-a625d872ca82?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcwNjMyNjE0Nw&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price: 500,
      location: "FlourCraft Mills",
      country: "India",
      contact:1111111111,
    },
    {
      title: "Aromatic & Medicinal Plants",
      description: "Plants with aromatic and medicinal properties, perfect for a health-conscious lifestyle.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1417533366444-43834ad6b3bb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcwNjMyNjE3MQ&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price: 60,
      location: "HerbalHeal Nurseries , Delhi",
      country: "India",
      contact:1111111111,
    },
    {
      title: "Haldi & Ubtan",
      description: "Turmeric (haldi) and ubtan for natural skincare and beauty rituals.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1615485500834-bc10199bc727?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcwNjMyNjE5Ng&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price: 75,
      location: "NaturalGlow Cosmetics",
      country: "India",
      contact:1111111111,
    },
    {
      title: "Cereals & Millets Products",
      description: "Nutrient-rich cereals and millets for a wholesome and balanced diet.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1684567866490-39787a539393?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcwNjMyNjIyMQ&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price: 560,
      location: "NutriGrain Farms , Punjab",
      country: "India",
      contact:1111111111,
    },
    {
      title: "Sugarcane",
      description: "Fresh and juicy sugarcane for extracting natural sweetness.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1585155113372-6c1808141bf3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcwNjMyNjI1NA&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price: 320,
      location: "SweetHarvest Plantations , Uttar Pradesh",
      country: "India",
      contact:1111111111,
    },
    {
      title: "OrganicGlow Cucumbers",
      description: "Crisp and organic cucumbers that bring a refreshing glow to your salads and snacks.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcwNjMyNjI5Mg&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price:500,
      location: "GlowGarden Fields , West Bengal",
      country: "India",
      contact:1111111111,
    },
    {
      title: "Pure Plume Pumpkins",
      description: "Organic pumpkins with a pure and rich flavor, perfect for autumn dishes and seasonal treats.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1506917728037-b6af01a7d403?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcwNjMyNjM2MQ&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price:400,
      location: "PumpkinPatch Farms , Orissa",
      country: "India",
      contact:1111111111,
    },
    {
      title: "Organic Oasis Papayas",
      description: "Exotic and sweet organic papayas, bursting with tropical goodness and natural sweetness.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1526318472351-c75fcf070305?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY5ODM3NzY5Nw&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price:400,
      location: "TropicalOasis Plantations , Gujarat",
      country: "India",
      contact:1111111111,
    },
    {
      title: "EcoLeaf Lettuce",
      description: "Fresh and organic lettuce leaves, perfect for salads, sandwiches, and healthy wraps.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1556781366-336f8353ba7c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcwNjMyNjQxMw&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price: 389,
      location: "LeafyHarvest Gardens , Nilgiri Mountains",
      country: "India",
      contact:1111111111,
    },
    {
      title: "PurePulse Lentils",
      description: "Organic lentils, packed with protein and essential nutrients for a hearty and healthy meal.",
      image:{
      filename: "productimage",
      url: "https://plus.unsplash.com/premium_photo-1671130295987-13d3b3b4e9dc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8dyxoLGZpdCxhdXRvLGRwcnx8fHx8fDE3MDU4NTkyMzI&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price:350,
      location: "PulseHarvest Fields , Chhatisgarh",
      country: "India",
      contact:1111111111,
    },
    {
      title: "Organic Tomatoes",
      description: "Juicy and organic tomatoes, vine-ripened for a burst of flavor in every bite.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1582284540020-8acbe03f4924?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcwNjMyNjQ2OQ&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price: 78,
      location: "VineHarvest Gardens , Bihar",
      country: "India",
      contact:1111111111,
    },
    {
      title: "Pure Ghee",
      description: "Clarified organic butter, crafted with care to achieve a golden and flavorful Ghee for cooking.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1573812461383-e5f8b759d12e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcwNjMyNjQ5Mg&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price: 350,
      location: "GlowDairy Farms , Gir Gujarat",
      country: "India",
      contact:1111111111,
    },
    {
      title: "Chillies",
      description: "Fresh, fiery red chillies harvested from local farms. These chillies are packed with flavor and spice, perfect for adding a kick to your favorite dishes.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1546860255-95536c19724e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcxMjQ4NTMxNw&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price: 200,
      location: "Green Valley Farms, Nashik, Maharashtra",
      country: "India",
      contact:1111111111,
    },
    {
      title: "Papaya",
      description: " Juicy and tropical papayas grown at Papaya Paradise Farm. Known for their vibrant orange flesh and sweet, musky flavor, papayas are rich in vitamins and digestive enzymes.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1526318472351-c75fcf070305?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY5ODM3NzY5Nw&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price: 600,
      location: "Papaya Paradise Farm, Madurai, Tamil Nadu",
      country: "India",
      contact:1111111111,
    },
    {
      title: "Dragon Fruit",
      description: "Exotic and visually stunning dragon fruits cultivated at Dragon Haven Farm. With its vibrant pink skin and speckled flesh, dragon fruit offers a mild, sweet flavor and is rich in antioxidants.",
      image:{
      filename: "productimage",
      url:"https://plus.unsplash.com/premium_photo-1667051230160-5906f5683a59?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcxMjQ4NjYyNQ&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price: 580,
      location: " Dragon Haven Farm, Andaman and Nicobar Islands, ",
      country: "India",
      contact:1111111111,
    },
    {
      title: "Corn",
      description: "olden ears of sweet corn, perfect for grilling or boiling, from Golden Harvest Farm. Each kernel bursts with sweetness and flavor, making it a summer favorite.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1554402100-8d1d9f3dff80?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcxMjQ4NTk5OQ&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price: 30,
      location: "Golden Harvest Farm, Lucknow, Uttar Pradesh, India.",
      country: "India",
      contact:1111111111,
    },
    {
      title: "Mangoes",
      description: "Fresh, and juicy mangoes ready to serve on your table.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1519096845289-95806ee03a1a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcxMjQ4NTcxOA&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price: 1090,
      location: "Mango farm, Talala, Gujarat",
      country: "India",
      contact:1111111111,
    },
    {
      title: "Guava",
      description: "Fragrant and flavorful guavas picked fresh from Guava Grove Farm. These round or pear-shaped fruits have green or yellow skin and pink or white flesh with a sweet, tropical aroma and taste.",
      image:{
      filename: "productimage",
      url: "https://images.unsplash.com/photo-1634014154598-f8f50ae6bf2a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcxMjQ4NzM5MA&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080",
      },
      price: 160,
      location: "Guava Grove Farm, Tamil Nadu",
      country: "India",
      contact:1111111111,
    }
  ]

  module.exports = {data:sampleData};
  